// Generated by CoffeeScript 1.6.2
(function() {
  var ASSETS, BEAR_IMG, Bear, ComboLabel, CountLabel, MAP_IMG, Message, MessageType, NicoLabel, ShitaMessage, StreamMessage, TextSize, TimerLabel, add, canvasContext, game, life, padding, rand, remove, timer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  enchant();

  BEAR_IMG = 'chara1.png';

  MAP_IMG = 'map1.png';

  ASSETS = [BEAR_IMG];

  canvasContext = null;

  TextSize = {
    Medium: {
      charWidth: 6,
      fontSize: 20
    },
    Large: {
      charWidth: 11,
      fontSize: 40
    }
  };

  game = null;

  timer = null;

  life = null;

  Function.prototype.property = function(prop, desc) {
    return Object.defineProperty(this.prototype, prop, desc);
  };

  rand = function(min, max) {
    if (max == null) {
      max = min;
      min = 0;
    }
    min = Math.floor(min);
    max = Math.floor(max);
    return min + Math.floor(Math.random() * max) % (max - min);
  };

  add = function(inst) {
    return game.currentScene.addChild(inst);
  };

  remove = function(inst) {
    return game.currentScene.removeChild(inst);
  };

  padding = function(num) {
    return ('00' + num).substr(-2);
  };

  Bear = (function(_super) {
    __extends(Bear, _super);

    function Bear() {
      Bear.__super__.constructor.call(this, 32, 32);
      this.image = game.assets[BEAR_IMG];
      this.x = game.width / 2;
      this.y = game.height / 2;
      this.vx = 2;
      this.vy = 2;
      add(this);
    }

    Bear.prototype.onenterframe = function() {
      this.x += this.vx;
      this.y += this.vy;
      if (!(0 <= this.x && this.x < game.width)) {
        this.vx = -this.vx;
      }
      if (!(0 <= this.y && this.y < game.height)) {
        return this.vy = -this.vy;
      }
    };

    return Bear;

  })(Sprite);

  NicoLabel = (function(_super) {
    __extends(NicoLabel, _super);

    function NicoLabel(x, y, color, textSize) {
      if (color == null) {
        color = '#ffffff';
      }
      this.textSize = textSize != null ? textSize : TextSize.Medium;
      NicoLabel.__super__.constructor.apply(this, arguments);
      this.x = x;
      this.y = y;
      this.color = color;
      this.font = "bold " + this.textSize.fontSize + "px Arial";
      add(this);
    }

    NicoLabel.prototype.setText = function(txt) {
      this.text = txt;
      canvasContext.font = this.font;
      return this.width = canvasContext.measureText(this.text).width;
    };

    return NicoLabel;

  })(Label);

  CountLabel = (function(_super) {
    __extends(CountLabel, _super);

    function CountLabel(x, y) {
      CountLabel.__super__.constructor.call(this, x, y);
      this._count = 0;
      this.label = '';
    }

    CountLabel.property('count', {
      get: function() {
        return this._count;
      },
      set: function(c) {
        this._count = c;
        return this.setText("" + this.label + this._count);
      }
    });

    return CountLabel;

  })(NicoLabel);

  ComboLabel = (function(_super) {
    var comboNum, lastComboFrame;

    __extends(ComboLabel, _super);

    comboNum = 0;

    lastComboFrame = 0;

    function ComboLabel(x, y) {
      ComboLabel.__super__.constructor.call(this, x, y, '#fff100');
      if (game.frame - lastComboFrame > game.fps) {
        comboNum = 0;
      }
      comboNum++;
      this.setText("Combo " + comboNum);
      timer.addTime(comboNum * 10);
      lastComboFrame = game.frame;
      this.MAX_AGE = 30;
    }

    ComboLabel.prototype.onenterframe = function() {
      this.y -= 1;
      this.opacity = 1.0 - (this.age / this.MAX_AGE);
      if (this.age > this.MAX_AGE) {
        return remove(this);
      }
    };

    return ComboLabel;

  })(NicoLabel);

  TimerLabel = (function(_super) {
    __extends(TimerLabel, _super);

    function TimerLabel(x, y) {
      TimerLabel.__super__.constructor.call(this, x, y);
      this.count = 0;
      this.update();
    }

    TimerLabel.prototype.update = function() {
      return this.setText(this.getTime());
    };

    TimerLabel.prototype.onenterframe = function() {
      if (game.frame % game.fps === 0) {
        this.count++;
        return this.update();
      }
    };

    TimerLabel.prototype.addTime = function(time) {
      this.count += time;
      if (this.count < 0) {
        this.count = 0;
      }
      return this.update();
    };

    TimerLabel.prototype.getMinute = function() {
      return Math.floor(this.count / 60);
    };

    TimerLabel.prototype.getSecond = function() {
      return this.count % 60;
    };

    TimerLabel.prototype.getTime = function() {
      return "" + (padding(this.getMinute())) + ":" + (padding(this.getSecond()));
    };

    return TimerLabel;

  })(NicoLabel);

  MessageType = {
    Normal: {
      color: '#ffffff',
      ontouch: function() {
        return timer.addTime(-10);
      }
    },
    Illegal: {
      color: '#ff0000',
      ontouch: function(msg, e) {
        return new ComboLabel(e.x, e.y);
      },
      onleave: function() {
        return life.count -= 1;
      }
    }
  };

  Message = (function(_super) {
    __extends(Message, _super);

    function Message(x, y, text, msgType) {
      this.msgType = msgType;
      Message.__super__.constructor.call(this, x, y, this.msgType.color, TextSize.Large);
      this.setText(text);
    }

    Message.prototype.ontouchstart = function(e) {
      var _base;

      if (typeof (_base = this.msgType).ontouch === "function") {
        _base.ontouch(this, e);
      }
      return remove(this);
    };

    Message.prototype.leave = function() {
      var _base;

      if (typeof (_base = this.msgType).onleave === "function") {
        _base.onleave(this);
      }
      return remove(this);
    };

    return Message;

  })(NicoLabel);

  StreamMessage = (function(_super) {
    __extends(StreamMessage, _super);

    function StreamMessage(text, msgType) {
      StreamMessage.__super__.constructor.call(this, game.width, 0, text, msgType);
      this.vx = -rand(2, 10);
      this.y = rand(game.height - 50);
    }

    StreamMessage.prototype.onenterframe = function() {
      this.x += this.vx;
      if (this.x + this.width < 0) {
        return this.leave();
      }
    };

    return StreamMessage;

  })(Message);

  ShitaMessage = (function(_super) {
    __extends(ShitaMessage, _super);

    function ShitaMessage(text, msgType) {
      ShitaMessage.__super__.constructor.call(this, 0, 0, text, msgType);
      this.x = (game.width - this.width) / 2;
      this.y = game.height / 5 * 4;
    }

    ShitaMessage.prototype.onenterframe = function() {
      if (this.age > game.fps * 2) {
        return this.leave();
      }
    };

    return ShitaMessage;

  })(Message);

  window.onload = function() {
    canvasContext = document.getElementById('dummyCanvas').getContext('2d');
    game = new Game(500, 400);
    game.fps = 3;
    game.preload(ASSETS);
    game.onload = function() {
      var gameover, scene;

      scene = game.rootScene;
      scene.backgroundColor = '#0f0f0f';
      scene.backgroundColor = '#00ff00';
      new Bear;
      timer = new TimerLabel(0, 0);
      life = new CountLabel(100, 0);
      life.label = 'Life : ';
      life.count = 1;
      gameover = false;
      return scene.onenterframe = function() {
        var i, n, _i, _ref;

        if (game.frame % game.fps === 0) {
          for (i = _i = 0, _ref = timer.getMinute() + 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
            n = rand(10);
            if (n === 0 || n === 1) {
              new StreamMessage('mmmmmmmmmmmm', MessageType.Illegal);
            } else if ((2 <= n && n < 5)) {
              new StreamMessage('wwwwwwwwwwww', MessageType.Normal);
            } else if ((5 <= n && n < 8)) {
              new ShitaMessage('熊大人気ｗｗｗ', MessageType.Normal);
            } else {
              new ShitaMessage('爆発汁', MessageType.Illegal);
            }
          }
        }
        if (life.count === 0 && !gameover) {
          alert("ゲームオーバー\n再生時間 " + (timer.getTime()));
          return gameover = true;
        }
      };
    };
    return game.start();
  };

}).call(this);
