// Generated by CoffeeScript 1.6.2
(function() {
  var ASSETS, BEAR_IMG, Message, StreamMessage, add, game, rand, remove,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  enchant();

  BEAR_IMG = 'chara1.png';

  ASSETS = [BEAR_IMG];

  game = null;

  rand = function(max) {
    return Math.floor(Math.random() * max);
  };

  add = function(inst) {
    return game.currentScene.addChild(inst);
  };

  remove = function(inst) {
    return game.currentScene.removeChild(inst);
  };

  Message = (function(_super) {
    __extends(Message, _super);

    function Message(x, y, text) {
      Message.__super__.constructor.call(this, text);
      this.x = x;
      this.y = y;
      this.color = '#ffffff';
      this.font = 'bold 24px Arial';
      add(this);
    }

    Message.prototype.ontouchstart = function(e) {
      return remove(this);
    };

    return Message;

  })(Label);

  StreamMessage = (function(_super) {
    __extends(StreamMessage, _super);

    function StreamMessage(text, vx) {
      this.vx = vx;
      StreamMessage.__super__.constructor.call(this, game.width, rand(game.height), text);
    }

    StreamMessage.prototype.onenterframe = function() {
      this.x += this.vx;
      if (this.x + this.width < 0) {
        return remove(this);
      }
    };

    return StreamMessage;

  })(Message);

  window.onload = function() {
    game = new Game(500, 500);
    game.fps = 30;
    game.preload(ASSETS);
    game.onload = function() {
      var scene;

      scene = game.rootScene;
      scene.backgroundColor = '#0f0f0f';
      return scene.onenterframe = function() {
        var i, _i, _results;

        if (game.frame % game.fps === 0) {
          _results = [];
          for (i = _i = 1; _i <= 10; i = ++_i) {
            _results.push(new StreamMessage('wwwwwwwwwwww', -rand(10)));
          }
          return _results;
        }
      };
    };
    return game.start();
  };

}).call(this);
